# Scientific Computing and Modelling in Python Part 1

## 3.1 What is data science and modelling?

Python is a powerful language that is used for analytics and modelling. A popular language in industry, it is heavily used in the **data science field** and gaining popularity in the econometrics field.

So what is data science? Data science is a multi-disciplinary field that uses scientific methods, processes, algorithms and systems to extract knowledge and insights from data in various forms, both structured and unstructured.


## Setting

Just a high level refresher, suppose we had a bunch of data collected on some [Pokemon](https://en.wikipedia.org/wiki/Pok%C3%A9mon). In particular, for each pokemon, we noted down their height and weight. In particular, we had the following observations:

- Pikachu: Height-120 and Weight-54
- Charmander: Height-132 and Weight-58
- Squirtle: Height-144 and Weight-68
- Raichu: Height-150 and Weight-70

We want to see if there is a **linear relationship** between the age and height of the Pokemon. That is, are the two _features_ for the Pokemon related?

More specifically, we want to investigate whether are _taller_ pokemon heavier?

Fortunately, using Python, we can investigate this!

## 3.2 NumPy Arrays

For the rest of this tutorial, we will be using [numpy arrays](https://www.machinelearningplus.com/python/numpy-tutorial-part1-array-python-examples/) rather than lists.

#### Remark
Why are we now working with numpy arrays rather than lists? A few reasons actually!

1) NumPy arrays are alot more efficient than lists. For example, if you had 10 different datasets to work with, storing it in a list of lists would take around 2 MB whilst storing it in a NumPy array would take around 20% of that. This is really important as this means you're laptop/desktop will be able to process the data MUCH faster and more efficiently.

2) NumPy arrays are quite similar to vectors in R or matrices in Matlab, hence you'll be able to port alot of the skills you learn here over.

3) NumPy arrays allows for vector/matrix operations in a much smoother manner. In general, we have access to more functions that can be useful to us.

In [1]:
# First we import numpy 
import numpy as np

In [2]:
# Creating arrays are quite easy. Recall how we created lists
my_list = [10, 20, 30, 40]

In [3]:
print(my_list)

[10, 20, 30, 40]


In [4]:
# So to create a NumPy array, we do something similar regarding the syntax of the list but we now wrap it
# in the np.array() function.

my_array = np.array([10, 20, 30, 40])

In [5]:
print(my_array)

[10 20 30 40]


Same effect!

In [6]:
# We can also just pass in a list variable into our numpy function.
my_array_two = np.array(my_list)
print(my_array_two)

[10 20 30 40]


#### Excercise

1) Try creating a numpy array of the list `["pika pika", "bulbasaur"]`. Does this work?

2) Generate a numpy array of every 4th number from 1-100. Recall the range function `range(0, 100, 4)` may help here.

Now where NumPy arrays come in really handy is vector operations. Let's see some examples.

In [7]:
# We have two lists.
x_one = [1,2,3,4,5]
x_two = [10,20,30,40,50]

# Let's add them together. What do you think we will get?
x_three = x_one + x_two
#print(x_three)

In [8]:
# So how would we actually add them together?

# Method 1:
x_three = []
for index, entry in enumerate(x_one):
    result = x_one[index] + x_two[index]
    x_three.append(result)
    
# Method 2: Faster way of the above
x_sum = [entry_one + entry_two for entry_one, entry_two in zip(x_one, x_two)]

Unecessarily difficult for a task that should seem easy!!! 

What happens if we use numpy?

In [9]:
x_one = np.array([1,2,3,4,5])
x_two = np.array([10,20,30,40,50])

print(x_one + x_two)

[11 22 33 44 55]


Too easy.

#### Excercise

1) Create a function that takes in two numpy arrays, subtract them from each other and return a numpy array containing the results.

2) (Extension) Given two numpy arrays (1 x n) and (n x 1), matrix multiply them together to get a single value. (You might want to Google what does @ in Python do)

In [10]:
# x_one @ x_two

Now that's very cool and all but what if we want to work with matrices instead?

It's easy, you insert in a `list of lists`. Simply put the list of numbers, followed by a `,` and then your next row of entries. Make sure the rows are of the same length (for linear algebra to work, it'll still work in Python)!

In [11]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
# What happens if not the same length
B = np.array([[1,2,3], [4], [7,8]])
print(B)

# Still works but generally not a good idea if you recall from your math classes...

[list([1, 2, 3]) list([4]) list([7, 8])]


In [13]:
# We also have some special functions to create certain matrices we may need in maths.

# A 2x3 matrix of 0.
zeros = np.zeros( (2, 3) )
print(zeros)
print("\n\n") # Just to make output easier to read.

# A 5x6 matrix of 1.
ones = np.ones( ( 5, 6) )
print(ones)
print("\n\n") # Just to make output easier to read.

# A 3x3 identity matrix (recall these are always square matrices, so we need to only specify row length).
identity = np.eye( (3) )
print(identity)

[[0. 0. 0.]
 [0. 0. 0.]]



[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


There are so many features for NumPy but one more important thing is access elements of our numpy array.

In [14]:
array = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12] ])
print(array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Lets say we want to access 4. It is in the **1st** row (remember we count from 0 in Python) and in the **0th** column.

In [15]:
# First specify row number and then column number.
array[1][0]

4

#### Excercise
1) Access the number 6 in `array`.

2) Access the number 11 in `array`.

What we just did is known as _indexing_. Now what if we want to grab an entire row? We use a technique called [slicing](https://machinelearningmastery.com/index-slice-reshape-numpy-arrays-machine-learning-python/).

To grab the 1st row (so [4, 5, 6] in our case), we specify the row and `,` to specify the columns we want from that row. If we leave out `,` we just get the entire row.

In [16]:
array[1]

array([4, 5, 6])

In [17]:
# This is equivalent to where the left and right of : is empty to grab anything.
array[1, :]

array([4, 5, 6])

In [18]:
# What if we want only the 1st and 2nd column. Recall that this will grab the 1st column and 2nd
# (but not 3rd because its exclusive)
array[1, 1:3]

array([5, 6])

In [19]:
# Grab first 2 rows and first 2 columns.
array[0:2, 0:2]

array([[1, 2],
       [4, 5]])

#### Excercise

Use the `array = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12] ])` to work on. Grab the following rows and columns from the array.

1) Grab the first 3 rows and first 2 columns.

2) Grab the first 3 rows and first column.

3) Grab the last 2 rows and last 2 columns.

## 3.3 Summary Statistics

When you're first given a dataset in data analysis, running some basics analysis to look at things such as summary statistics can go a long way. Here we can keep using the Numpy library to help us.

In [25]:
# Creates a 1x10 array from 0-9.
fake_data = np.arange(10)
print(fake_data)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
# Let's say we want to get the mean. It is quite easy. The function is `mean()`.
np.mean(fake_data)

4.5

In [27]:
# If we want to get the variance, it is quite similar.
np.var(fake_data)

8.25

#### Excercise

1) Calculate the standard deviation of `fake_data`. Use the function `np.std()` OR a combination of `np.sqrt()` (square roots numbers) and `np.var()`.

In [28]:
np.sqrt(np.var(fake_data))

2.8722813232690143

In [30]:
np.std(fake_data)

2.8722813232690143

#### Excercise

Suppose we had a 5 x 2 matrix. `A = np.array([ [5, 10, 15, 20, 25], [6, 12, 18, 24, 30] ])`.

1) Calculate the mean and variance of the first column.

2) Do the same thing for the second column.

Going back to the earlier Pokemon example. Let's say we want to compute the **correlation** between two arrays. It's quite easy now with numpy!

In [31]:
height = np.array([120, 132, 144, 150])
weight = np.array([54, 58, 68, 70])

We can use the `np.corrcoef` function.

In [32]:
np.corrcoef(height, weight)

array([[1.        , 0.98280838],
       [0.98280838, 1.        ]])

What's this? We were given back a 2x2 matrix. This is simply a correlation matrix where the diagonal are simply the correlation of the array with itself. So the top left `1` shows the correlation of height with height is 1 (duh!). Hence we are only interested in off-diagonals. This is a symmetric matrix so it doesn't matter which off-diagonal we pick.

In [34]:
# We can access the off-diagonal using the same numpy techniques as before for indexing.
print(np.corrcoef(height, weight)[0][1])

# We can also get the other off-diagonal too.
print(np.corrcoef(height, weight)[1][0])

0.9828083836176786
0.9828083836176787


## 3.4 Regressions

Now computing the correlation between variables is good if we want to see whether is there a linear relationship between two variables. However, what if we wanted to know whether does a Pokemon being taller *causes* them to be heavier? This is where regressions come into play. The let us see how the dependent/response variable (weight) is affected by the independent/control/feature variable (height).

We shift gears again to now using `StatsModel` package.

First, we need to create a `linear regression object` which can be used to store all the information about our regression. You can think of it as a very fancy list if it helps.

Now we need to do the actual regression on the data. Note that the independent (height) variable goes first in terms of arguments for the `fit()` function.

In [1]:
import statsmodels.api as sm
#import statsmodels.formula.api as smf

In [2]:
height = np.array([120, 132, 144, 150])
weight = np.array([54, 58, 68, 70])

NameError: name 'np' is not defined

In [ ]:
model = sm.OLS(weight, height)
model_result = model.fit()
print(model_result.summary())

Notice we don't have an intercept. If we want to add it, we need to specify beforehand in our independent variable array.

In [3]:
height_modified = sm.add_constant(height)

NameError: name 'height' is not defined

In [72]:
print(height_modified)

[[  1. 120.]
 [  1. 132.]
 [  1. 144.]
 [  1. 150.]]


Now we have constants for us to have an intercept in our regression.

In [73]:
model = sm.OLS(weight, height_modified)
model_result = model.fit()
print(model_result.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.966
Model:                            OLS   Adj. R-squared:                  0.949
Method:                 Least Squares   F-statistic:                     56.67
Date:                Sun, 17 Mar 2019   Prob (F-statistic):             0.0172
Time:                        17:39:45   Log-Likelihood:                -6.5203
No. Observations:                   4   AIC:                             17.04
Df Residuals:                       2   BIC:                             15.81
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        -15.3898     10.383     -1.482      0.2

/usr/local/lib/python3.7/site-packages/statsmodels/stats/stattools.py:72: ValueWarning: omni_normtest is not valid with less than 8 observations; 4 samples were given.
  "samples were given." % int(n), ValueWarning)


That looks better now!

If we want to access the coefficients, it's easy! Just do `.params`. We can then access the parameter values using numpy indexing as usual.

In [4]:
print(model_result.params)

NameError: name 'model_result' is not defined

If we want to access the test-statistics on the parameters, we can go `.tvalues`.

In [77]:
print(model_result.tvalues)

[-1.48216504  7.52809552]


When in doubt on what you can get, just go `model_result.` and then hit the `tab` button which will bring a list of things you can access from the variable. Such as the $R^2$.

In [78]:
model_result.rsquared

0.9659123189091942

#### Excercise

1. Create your own numpy arrays and run your own regressions. Ask for help if needed! Try doing it with 2 or more variables.

2. (Extension). If you have done ECMT2160, you would have seen the `logit` regression. Try implementing [it](https://www.statsmodels.org/dev/generated/statsmodels.discrete.discrete_model.Logit.html). Instead of `sm.OLS`, use `sm.Logit` and keep everything else the same.